name: dotnet integration

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and deploy the docker image
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'social-network-ip' }}

      run: |
        heroku container:login
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME